"""全局常量配置。"""

import os


# 集市配置
DEFAULT_MARKET_STOCK_INCREASE = 10
KAPPA = {
    "comsumable": 0.11,
    "valuable": 0.11,
}
SIGMA = {
    "comsumable": 0.15,
    "valuable": 0.4,
}
MARKET_PRICE_CHANGE_PROB = 0.85
INTEL_ACCURACY_MIN = 0.60
INTEL_ACCURACY_MAX = 0.95

# 模型配置
ACT_MODEL_NAME = "deepseek-ai/DeepSeek-V4-Flash"
PLAN_MODEL_NAME = "deepseek-ai/DeepSeek-V4-Flash"
REFLECT_MODEL_NAME = "deepseek-ai/DeepSeek-V4-Flash"

# 角色属性配置
HUNGER_DECAY_PER_DAY = 8
THIRST_DECAY_PER_DAY = 10
FATIGUE_DECAY_PER_DAY = -20
FATIGUE_DECAY_PER_ACTION = 5
ATTR_CN_MAP = {
    "hunger": "饱食度",
    "thirst": "水分值",
    "fatigue": "精神值",
}

# 游戏机制配置
NPC_WIN_MONEY_THRESHOLD = 10000
PLAYER_WIN_MONEY_THRESHOLD = 10000
WIN_CONDITION = PLAYER_WIN_MONEY_THRESHOLD
RANDOM_EVENT_PORB = 0.1

# 运行主循环配置
USE_ACION_LAYER = True
TICK_INTERVAL_SECONDS = 1.0
ACTION_LAYER_CONNECT_POLL_SECONDS = 1.0

# 调试日志配置
ENABLE_DEBUG_PROMPT_LOG = False

"""运行时参数配置。"""

# 动作重试与重规划
MAX_ACTION_RETRIES = 2
MAX_REPLAN_AFTER_ACTION_ERROR = 2

# 行为保护阈值
REPEAT_ACTION_GUARD_THRESHOLD = 2
REPEAT_TRADE_SAME_ITEM_THRESHOLD = 3
ALLOW_OPPOSITE_TRADE_SAME_ITEM_SAME_DAY = False

# 反思触发间隔
REFLECT_MIN_INTERVAL_STEPS = 20

# 生存危险阈值
SURVIVAL_HUNGER_THRESHOLD = 20.0
SURVIVAL_THIRST_THRESHOLD = 20.0
SURVIVAL_FATIGUE_THRESHOLD = 15.0
